var nombre = "pedro";
console.log(typeof nombre); String
var edad = 10;
console.log(typeof edad); Number
var estado = true;
console.log(typeof estado); Boolean
var undef = undefined;
console.log(typeof undef); undefined
var test = null;
console.log(typeof test); Object
nombre = 50;
console.log(typeof nombre); Number

var apellido = "Florez";
var apellidoUpperCase = apellido.toUpperCase();
console.log(apellido); Florez
console.log(apellidoUpperCase); FLOREZ 

var list = [];




